using System;
using System.Collections.Generic;
using System.Text;
using Utils.NET.IO;

namespace Utils.NET.Net.Udp.Packets
{
    public class UdpConnect : UdpPacket
    {
        public override UdpPacketType Type => UdpPacketType.Connect;

        /// <summary>
        /// Salt generated by the client and sent to the server
        /// </summary>
        public ulong fromSalt;

        public UdpConnect(ulong fromSalt) => this.fromSalt = fromSalt;

        protected override void Read(BitReader r)
        {
            fromSalt = r.ReadUInt64();
        }

        protected override void Write(BitWriter w)
        {
            w.Write(fromSalt);
        }
    }
}
