using System;
using System.Collections.Generic;
using System.Text;
using Utils.NET.IO;

namespace Utils.NET.Net.Udp.Packets
{
    public class UdpChallenge : UdpPacket
    {
        public override UdpPacketType Type => UdpPacketType.Challenge;

        /// <summary>
        /// Salt received from the client
        /// </summary>
        public ulong fromSalt;

        /// <summary>
        /// Salt generated by the server
        /// </summary>
        public ulong toSalt;

        public UdpChallenge(ulong fromSalt, ulong toSalt)
        {
            this.fromSalt = fromSalt;
            this.toSalt = toSalt;
        }

        protected override void Read(BitReader r)
        {
            fromSalt = r.ReadUInt64();
            toSalt = r.ReadUInt64();
        }

        protected override void Write(BitWriter w)
        {
            w.Write(fromSalt);
            w.Write(toSalt);
        }
    }
}
